kind: ConfigMap
apiVersion: v1
metadata:
  name: ambari-agent-scripts
  namespace: ambari
data:
  write-custom-hostname.sh: |
      #!/bin/bash
      HOSTNAME=$(hostname)
      echo -e "#/bin/bash\necho ${HOSTNAME}.amb-agent.ambari.svc.cluster.local" > /etc/ambari-agent/conf/internal-hostname.sh
      # cat /etc/hosts | sed -e "s/$HOSTNAME/$(/etc/ambari-agent/conf/internal-hostname.sh)/" > /etc/hosts
      echo "$(/etc/ambari-agent/conf/internal-hostname.sh)" > /etc/hostname
      hostname $(/etc/ambari-agent/conf/internal-hostname.sh)