---
apiVersion: v1
kind: ReplicationController
metadata:
  name: amb-agent
  namespace: ambari
  labels:
    name: amb-agent
spec:
  replicas: 5
  selector:
    name: amb-agent
  template:
    metadata:
      labels:
        name: amb-agent
    spec:
      containers:
      - name: amb-agent
        # image: hortonworks/ambari-agent:2.2.1-v20
        image: registry.cn-hangzhou.aliyuncs.com/tospur/amb-agent:v2.4
        securityContext:
          privileged: true
        # resources:
        #   requests:
        #     memory: "16G"
        #     cpu: "2000m"
        #   limits:
        #     memory: "20G"
        #     cpu: "3000m"
        volumeMounts:
            - name: ambari-conf
              mountPath: /etc/systemd/system/ambari-agent.service.d
            - name: ambari-scripts
              mountPath: /scripts
            - name: haddop-data
              mountPath: /hadoop
            - name: hadoop-log
              mountPath: /var/log
        env: 
          - name: AMBARI_SERVER
            value: ambari-server.ambari.svc.cluster.local
      volumes:
          - name: ambari-conf
            configMap: 
                name: ambari-agent
          - name: ambari-scripts
            configMap: 
                name: ambari-agent-scripts
          - name: haddop-data
            hostPath:
              path: /home/hadoop_data
          - name: hadoop-log
            hostPath:
              path: /home/hadoop_log

