apiVersion: v1
kind: Service
metadata:
  namespace: ambari
  name: agent
  labels:
    name: agent
spec:
  ports:
  - port: 80
    name: nousage
  clusterIP: None
  selector:
    name: agent
---
kind: StatefulSet
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: ambari
  name: amb
spec:
  serviceName: "agent"
  replicas: 3
  template:
    metadata:
      labels:
        name: agent
    spec:
      containers:
      - name: amb-agent
        # image: hortonworks/ambari-agent:2.2.1-v20
        image: registry.cn-hangzhou.aliyuncs.com/tospur/amb-agent:v2.4
        securityContext:
          privileged: true
        volumeMounts:
            - name: ambari-conf
              mountPath: /etc/systemd/system/ambari-agent.service.d
            - name: ambari-scripts
              mountPath: /tmp/scripts
            - name: haddop-data
              mountPath: /hadoop
            - name: hadoop-log
              mountPath: /var/log
        env: 
          - name: AMBARI_SERVER
            value: ambari-server.ambari.svc.k8s
      volumes:
          - name: ambari-conf
            configMap: 
                name: ambari-agent
          - name: ambari-scripts
            configMap: 
                name: ambari-agent-scripts
          - name: haddop-data
            persistentVolumeClaim:
              claimName: hadoop-data-claim
          - name: hadoop-log
            persistentVolumeClaim:
              claimName: hadoop-log-claim