---
apiVersion: v1
kind: ReplicationController
metadata:
  name: amb-httpd
  namespace: ambari
  labels:
    name: amb-httpd
spec:
  replicas: 1
  selector:
    name: amb-httpd
  template:
    metadata:
      labels:
        name: amb-httpd
    spec:
      containers:
      - name: amb-httpd
        image: registry.cn-hangzhou.aliyuncs.com/tospur/httpd:latest
        securityContext:
          privileged: true
        volumeMounts:
            - name: httpd-data
              mountPath: /usr/local/apache2/htdocs/
      nodeSelector:
        role: master
      volumes:
          - name: httpd-data
            hostPath:
              path: /home/hdp_httpd_home

---
apiVersion: v1
kind: Service
metadata:
  name: amb-httpd
  namespace: ambari
  labels:
    name: amb-httpd
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      name: web
      targetPort: 80
      protocol: TCP
  selector:
    name: amb-httpd
