---
apiVersion: v1
kind: ReplicationController
metadata:
  name: amb-mysql
  namespace: ambari
  labels:
    name: amb-mysql
spec:
  replicas: 1
  selector:
    name: amb-mysql
  template:
    metadata:
      labels:
        name: amb-mysql
    spec:
      containers:
      - name: amb-mysql
        image: mysql
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: amb-mysql
  namespace: ambari
  labels:
    name: amb-mysql
spec:
  ports:
    # the port that this service should serve on
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    name: amb-mysql
